### ISSUE TITLE
[Issue]: The latest version in the market stays at v0.0.11alpha

### ISSUE THREAD

**Issue by byheaven** [hkgnp/logseq-powertags-plugin#10]
### Plugin Version

v0.0.11alpha

### Logseq Version

v0.8.15

### What browsers are you seeing the problem on?

MacOS

### What happened?

The latest version of powertags in the market stays at v0.0.11alpha. Not v0.0.3

**Comment by benjypng** [comment]
When I install it, it says v0.0.3 though. Where are you seeing that it's v0.0.11alpha?

**Comment by byheaven** [comment]
I installed the old version several days ago. When I check for updates in the market, it shows v0.0.11alpha is up to date. Maybe a reinstallation is needed?

**Comment by byheaven** [comment]
And from the GitHub homepage:
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/30173023/211289559-1c077901-bcfb-49d8-b7e8-1d513f064a3f.png">

**Comment by byheaven** [comment]
I just reinstalled and it's at v0.0.3 now. I think it maybe relate to the different release tags or something?

**Comment by benjypng** [comment]
I see. It is likely due to my inclusion of text in the versioning.

**Comment by hkgnp** [comment]
Yes you are right. I should not have labelled my versioning this way!Regards,ben On 9 Jan 2023, at 6:50 PM, Yu Bai ***@***.***> wrote:﻿
I just reinstalled and it's at v0.0.3 now. I think it maybe relate to the different release tags or something?
