### ISSUE TITLE
[Issue]: powertags do not populate when a bullet starts with a tag.

### ISSUE THREAD

**Issue by ahpatel** [hkgnp/logseq-powertags-plugin#12]
### Plugin Version

v0.1.0

### Logseq Version

v0.8.16

### What browsers are you seeing the problem on?

Windows, MacOS

### What happened?

powertags do not populate when a bullet starts with a normal tag.

https://user-images.githubusercontent.com/9514136/214165934-b4883504-5831-4485-b822-b52d176c5f7a.mov

**Comment by ahpatel** [comment]
@hkgnp tried this plugin again with the recent changes, but still unusable with my workflow because many of my bullets start with a standard tag -- which powertags doesn't support.  

Is this something you could explore fixing, or are there limitation?

**Comment by benjypng** [comment]
Fixed in latest version.
