### ISSUE TITLE
I suspect the plugin is still in alpha phase?

### ISSUE THREAD

**Issue by thibaultmol** [hkgnp/logseq-powertags-plugin#13]
### Plugin Version

n/a

### Logseq Version

n/a

### What browsers are you seeing the problem on?

Linux

### What happened?

Consider using the github 'projects' section to make a roadmap of the items that need to be added/Fixed before stable release and such

**Comment by benjypng** [comment]
@thibaultmol thanks for the suggestion mate! all my plugins are technically in "alpha" phase 😂

I am actually doing these plugins as a hobby given that I've a full-time job not related to coding, hence the releases and feature plans are mostly unplanned.
