### ISSUE TITLE
What is the autoparse setting for?: 

### ISSUE THREAD

**Issue by TookiTheGreat** [hkgnp/logseq-powertags-plugin#14]
### Plugin Version

0.1.0

### Logseq Version

0.8.16

### What browsers are you seeing the problem on?

MacOS

### What happened?

There is an option to set Auto Parse to evaluate what is between braces but I can't find any explanation of how to use this. Can you give some examples of how to use this feature?

**Comment by benjypng** [comment]
It is to address this feature request: https://github.com/hkgnp/logseq-powertags-plugin/issues/8
