### ISSUE TITLE
[Feature request]: Have some properties autofilled using dynamic variables

### ISSUE THREAD

**Issue by TookiTheGreat** [hkgnp/logseq-powertags-plugin#15]
### Plugin Version

0.1.0

### Logseq Version

0.8.17

### What browsers are you seeing the problem on?

MacOS

### What happened?

I have some properties that I would love to have autofilled using dynamic variables: date, month, current time. It would be great if we could use Logseq dynamic variables such as %today%, %this month% and %now% for this, so every time we use a power tag, those values get automatically filled in.

**Comment by benjypng** [comment]
Available in latest version.
