### ISSUE TITLE
[Feature Request]: Drop-down menu with matched property values and remove "..."

### ISSUE THREAD

**Issue by NikitaVisitor** [hkgnp/logseq-powertags-plugin#16]
### Plugin Version

1.0.4

### Logseq Version

0.9.3

### What browsers are you seeing the problem on?

MacOS

### What happened?

It would be great if, after adding properties, I could access a drop-down menu with matched property values. Just as if I had entered "::".

Also in my opinion it would be convenient to remove "..." when properties are created so that you can immediately enter a value without wasting time deleting three characters.

**Comment by benjypng** [comment]
Could you elaborate on what the drop-down menu means? Since the properties are already added?

**Comment by NikitaVisitor** [comment]
I'll try to explain it better.
Logseq when entering :: shows a list of properties, and after selecting a property shows the values that were entered for this property earlier.
video from logseq devs
https://www.loom.com/share/27804e1bcd7b4e4bbf71ec14956c42fe

If I enter #books, then powertags adds the author/year/genre properties, but I haven't found a way to open the list of previously entered values for these properties, as if I clicked :: and then selected the property.

The metadata menu plugin for obsidian solves this problem like this - you can put the cursor on the property line after :: and press the space bar, then a list of previously entered values appears. Or if the value is not entered, then it would be enough to simply start editing the block in which there is a property in order for the list of previously entered values to open.

**Comment by benjypng** [comment]
I see what you mean. The dropdown selection is triggered by the specific behaviour of `shift + enter`, and then two `:`. Unfortunately, this can't be replicated in the plugin. However, once the database version is out, it should be easier to select values for block properties.
