### ISSUE TITLE
[Issue]: when add new property, this property is added to query table blocks too, which is not needed

### ISSUE THREAD

**Issue by FelixHuoEZ** [hkgnp/logseq-powertags-plugin#17]
### Plugin Version

1.0.4

### Logseq Version

0.9.4

### What browsers are you seeing the problem on?

Windows

### What happened?

when add new property, this property is added to query table blocks too, which is not needed

**Comment by benjypng** [comment]
I am not sure I understand. Do you have some specific examples to share?

**Comment by FelixHuoEZ** [comment]
Sorry, I cannot remember the issue either, so I closed it now. If the issue arises again, I'll reopen it.
