### ISSUE TITLE
[Issue]: not support for quote block in a property in power tag

### ISSUE THREAD

**Issue by FelixHuoEZ** [hkgnp/logseq-powertags-plugin#19]
### Plugin Version

1.0.4

### Logseq Version

0.9.6

### What browsers are you seeing the problem on?

Windows

### What happened?

When I add a quote block in a property of powertag, all the property field will be empty.

**Comment by benjypng** [comment]
I don't think quote blocks are meant to be used in block properties. Unless I am misunderstanding the issue. Feel free to re-open this issue if so.
