### ISSUE TITLE
Can't create power tag

### ISSUE THREAD

**Issue by xoyk** [hkgnp/logseq-powertags-plugin#2]
What I was doing: 

1. create a new block with #movies hashtag
2. run slash-command /Create power tag
3. after I have added property names and click "save" message "Please key in at least one property or ensure
a tag is selected"

See the attached video with bug reproducing. I tried it on two Logseq instance - my regular one and clean one (without any plugins or themes, except powertags-plugin). 

https://user-images.githubusercontent.com/1499826/208747477-0e907b31-c678-4285-9980-3be76aad32e4.mov

**Comment by benjypng** [comment]
Hi, you have to press "Enter" before clicking save.

**Comment by xoyk** [comment]
Oh, silly me. It was not obvious, that I have to press Enter to save a property name ))

Thanks, the plugin works as excepted. Sorry for false issue :)
