### ISSUE TITLE
[Issue]: Including index like (123.) in the start of a block title leads to incorrect format

### ISSUE THREAD

**Issue by e0lithic** [hkgnp/logseq-powertags-plugin#20]
### Plugin Version

v1.0.4

### Logseq Version

v0.9.8

### What browsers are you seeing the problem on?

Windows

### What happened?

<img width="595" alt="image" src="https://github.com/hkgnp/logseq-powertags-plugin/assets/11680315/8a2bccb2-8026-4412-8015-897f29c864ec">

As evident in the second case adding a "." after the number causes the properties to be rendered incorrectly.

**Comment by benjypng** [comment]
This issue should be filed with Logseq. Typing `3456.` causes Logseq to interpret is an index, e.g. a numbered list, and properties get shifted up. It is not a plugin issue.
