### ISSUE TITLE
Doesn't apply to page-level tags

### ISSUE THREAD

**Issue by rben01** [hkgnp/logseq-powertags-plugin#21]
### Plugin Version

1.0.4

### Logseq Version

0.9.8

### What browsers are you seeing the problem on?

MacOS

### What happened?

It seems that powertags only apply to blocks with the tag. It would be nice if when tagging a page with the `tags` property, power tags still applied. E.g.:

```
# My Page Title
tags:: #my-powertag
// insert powertag’s fields here //
```

**Comment by benjypng** [comment]
This plugin only works with hashtags defined at the block level, e.g. `#movie`.

Have updated the README for better clarity.
