### ISSUE TITLE
[Issue]: Stopped working after strange behavior editing tags

### ISSUE THREAD

**Issue by poelzi** [hkgnp/logseq-powertags-plugin#23]
### Plugin Version

1.0.4

### Logseq Version

0.9.2

### What browsers are you seeing the problem on?

Linux

### What happened?

I was editing a new Tag, I added #ketostix and wanted to set the label "mmol_L". The ui started to behave strange, I deleted the powertag and created a new one.
For $reasons, the plugin does not replace any tags anymore. Tried all settings, disabled all other plugins. Nothing in the logs, even with verbose on.
When I press the apply button, no tags get changed, also no error in the logs.

**Comment by poelzi** [comment]
I misinterpreted the effects of the bug I encountered since I often create single tag blogs.
I think https://github.com/hkgnp/logseq-powertags-plugin/blob/fb5092f601769300e6e08ef915ef955fe6ee4166/src/utils/findTag.ts#L14 is the culpit.

Is there a reason to exclude blocks that are only a powertag with no other words ?

**Comment by benjypng** [comment]
Given that the database feature is being developed by the Logseq team as a core feature, I will be more selective about making changes as the work will all be wasted when the feature is released.
