### ISSUE TITLE
Delete function doesnt work properly

### ISSUE THREAD

**Issue by Slabhub** [hkgnp/logseq-powertags-plugin#6]
delete powertags from list with "powertaglabel x" chips  sometimes works, sometimes doesnt.

**Comment by benjypng** [comment]
Do you have a screenshot or a specific example to test?On 27 Dec 2022, at 4:07 AM, Slabhub ***@***.***> wrote:﻿
delete powertags from list with "powertaglabel x" chips  sometimes works, sometimes doesnt.

**Comment by Slabhub** [comment]
screenrecord : 
https://ibb.co/bs4gf8G

**Comment by Slabhub** [comment]
i tried at macbook pro m1 pro and same result  :(

**Comment by benjypng** [comment]
Hi, what version of the plugin and Logseq are you on?

**Comment by Slabhub** [comment]
0,8,14

**Comment by benjypng** [comment]
How about the plugin?

**Comment by Slabhub** [comment]
0,0,01 but now i update logseq to 0.8.15 and works now

**Comment by benjypng** [comment]
Great!
