### ISSUE TITLE
Broken in 0.8.15

### ISSUE THREAD

**Issue by kerim** [hkgnp/logseq-powertags-plugin#7]
Since I updated the plugin is not adding the values anymore after hitting return. I am using version 0.0.1 (but updated after updating Logseq, so don't know if this version was having problems before or not, the alpha version I was using before was fine).

**Comment by benjypng** [comment]
Hi, could you screenshot the developer console please?

**Comment by kerim** [comment]
After I enter the (already defined) power tag I get two items in the developer console that look like this:

instrument.js:191 D:Search > Transact blocks!: [path to my graph]
instrument.js:191 D:Search > Transact pages!:  [path to my graph]

All the other console contents are sync related.

**Comment by benjypng** [comment]
Hmm, I am on v0.8.15 and have no issues with the plugin so far. Could you help to check the plugin settings `json` file? Should be in `.logseq/settings/logseq-powertags-plugin.json`.

**Comment by kerim** [comment]
```
{
  "addTypeProperty": false,
  "disabled": false,
  "savedTags": {
    "#oral-defense": [
      "Thesis-type",
      "Defense-date",
      "Student",
      "Committee",
      "Title"
    ],
    "#event": [
      "start-date",
      "end-date",
      "event-type"
    ]
  }
}
```

**Comment by benjypng** [comment]
May I suggest:

1) uninstall plugin
2) close logseq
3) delete `logseq-powertags-plugin.json` and `logseq-powertags-plugin_layouts.json` from the `.logseq/settings` folder
4) open logseq
5) reinstall plugin
6) e-creating your tags to see if the issue still persists? 

could be a migration issue.

**Comment by kerim** [comment]
This fixed it. Thanks.
