### ISSUE TITLE
Feature request: parse values on entry

### ISSUE THREAD

**Issue by kerim** [hkgnp/logseq-powertags-plugin#8]
If I have a power tag #meeting with the values "date" and "person" I'd like to write this:

#meeting {2022-12-30, John}

and have it parsed so that it would become:

#meeting 
date:: 2022-12-30
person: John

I hope that makes sense?

**Comment by benjypng** [comment]
Please try v0.1.0. Do remember to turn on auto-parse in the plugin settings.

**Comment by kerim** [comment]
Works great. thanks!

**Comment by TookiTheGreat** [comment]
I will give this a shot, thanks.
