### ISSUE TITLE
Feature Request: Drag to Reorder Attributes

### ISSUE THREAD

**Issue by ahpatel** [hkgnp/logseq-powertags-plugin#9]
### Plugin Version

v0.0.3

### Logseq Version

v0.8.15

### What browsers are you seeing the problem on?

Windows, MacOS

### What happened?

As I iterate on the use of powertags and their attributes, I can see a need for reordering the attribute list.  

It would be nice to drag existing attributes via the mouse to reorder them in the powertags UI.

And, after reordering, I'd expect that the "Apply All" option would reorder attributes on any existing block

**Comment by benjypng** [comment]
Hi, thanks for the FR.
May I know why is it necessary to reorder the attributes list?

**Comment by ahpatel** [comment]
It's a minor thing, but here's an example..

If I build a powertag (i.e., #meeting) and have the attributes of company, date, objective.  Then, at a later point, I realize I want to add a new attribute - i.e., participants - right after company.  It would currently append to the end.  

It's not the end of the world to go into the settings file and reorder when needed so may not be worth the overhead if no one else is asking for it.

**Comment by zolrath** [comment]
I'd also like to be able to reorder attributes!

**Comment by FelixHuoEZ** [comment]
+1 for this feature. It is necessary to clarify the significance of properties.

**Comment by benjypng** [comment]
Available in the latest version.
